import { Lead, Dealer, Staff, ActivityItem, FollowUpItem, NotificationItem, CRMSettings } from './types';

export const INITIAL_STAFF: Staff[] = [
  {
    id: 'staff-1',
    employeeId: 'EMP-010',
    name: 'John Doe',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    email: 'john.doe@crmadmin.com',
    phone: '+1 (555) 234-5678',
    role: 'Senior Account Exec',
    department: 'Enterprise Sales',
    assignedLeadsCount: 142,
    convertedLeadsCount: 98,
    conversionRate: 69,
    performanceScore: 94,
    status: 'Active',
    joinedDate: '2023-03-15',
    location: 'Seattle, WA',
    pendingFollowUps: 8,
    attendanceRate: 98,
  },
  {
    id: 'staff-2',
    employeeId: 'EMP-014',
    name: 'Anna Smith',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    email: 'anna.smith@crmadmin.com',
    phone: '+1 (555) 345-6789',
    role: 'Regional Manager',
    department: 'Automotive Network',
    assignedLeadsCount: 128,
    convertedLeadsCount: 82,
    conversionRate: 64,
    performanceScore: 91,
    status: 'Active',
    joinedDate: '2022-11-01',
    location: 'Austin, TX',
    pendingFollowUps: 5,
    attendanceRate: 97,
  },
  {
    id: 'staff-3',
    employeeId: 'EMP-022',
    name: 'Sarah J.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    email: 'sarah.j@crmadmin.com',
    phone: '+1 (555) 456-7890',
    role: 'Sales Director',
    department: 'Dealer Relations',
    assignedLeadsCount: 195,
    convertedLeadsCount: 146,
    conversionRate: 75,
    performanceScore: 98,
    status: 'Active',
    joinedDate: '2021-08-20',
    location: 'Seattle, WA',
    pendingFollowUps: 11,
    attendanceRate: 99,
  },
  {
    id: 'staff-4',
    employeeId: 'EMP-029',
    name: 'Mike K.',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    email: 'mike.k@crmadmin.com',
    phone: '+1 (555) 567-8901',
    role: 'Sales Representative',
    department: 'Commercial Accounts',
    assignedLeadsCount: 110,
    convertedLeadsCount: 58,
    conversionRate: 53,
    performanceScore: 84,
    status: 'Active',
    joinedDate: '2024-01-10',
    location: 'Denver, CO',
    pendingFollowUps: 14,
    attendanceRate: 95,
  },
  {
    id: 'staff-5',
    employeeId: 'EMP-035',
    name: 'David R.',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    email: 'david.r@crmadmin.com',
    phone: '+1 (555) 678-9012',
    role: 'CRM Specialist',
    department: 'Inbound Growth',
    assignedLeadsCount: 88,
    convertedLeadsCount: 52,
    conversionRate: 59,
    performanceScore: 88,
    status: 'Active',
    joinedDate: '2023-07-12',
    location: 'Chicago, IL',
    pendingFollowUps: 4,
    attendanceRate: 96,
  },
  {
    id: 'staff-6',
    employeeId: 'EMP-041',
    name: 'Rachel Taylor',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    email: 'rachel.t@crmadmin.com',
    phone: '+1 (555) 789-0123',
    role: 'Senior Account Exec',
    department: 'Enterprise Sales',
    assignedLeadsCount: 94,
    convertedLeadsCount: 56,
    conversionRate: 60,
    performanceScore: 87,
    status: 'On Leave',
    joinedDate: '2023-09-01',
    location: 'New York, NY',
    pendingFollowUps: 2,
    attendanceRate: 92,
  },
  {
    id: 'staff-7',
    employeeId: 'EMP-052',
    name: 'Alex Martinez',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    email: 'alex.m@crmadmin.com',
    phone: '+1 (555) 890-1234',
    role: 'Support Lead',
    department: 'Customer Success',
    assignedLeadsCount: 45,
    convertedLeadsCount: 22,
    conversionRate: 49,
    performanceScore: 82,
    status: 'Active',
    joinedDate: '2024-03-18',
    location: 'Miami, FL',
    pendingFollowUps: 6,
    attendanceRate: 94,
  }
];

export const INITIAL_DEALERS: Dealer[] = [
  {
    id: 'dealer-1',
    dealerCode: 'DLR-1042',
    name: 'Apex Motors',
    company: 'Apex Auto Group Inc.',
    contactPerson: 'Robert Vance',
    phone: '+1 (206) 555-0192',
    email: 'contact@apexautogroup.com',
    location: 'Seattle, WA',
    region: 'Northwest',
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Sarah J.',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    totalLeads: 1240,
    convertedLeads: 843,
    status: 'Active',
    lastActivity: '10 mins ago',
    joinedDate: '2022-04-12',
    rating: 4.9,
    revenue: 4280000,
    tier: 'Platinum',
    notes: [
      {
        id: 'dn-1',
        authorName: 'Sarah J.',
        authorRole: 'Sales Director',
        content: 'Apex added 3 new showroom locations in Bellevue. High volume dealership doing steady 68% conversion.',
        createdAt: '2026-08-28 14:30',
        pinned: true,
      }
    ],
    documents: [
      {
        id: 'doc-d1',
        name: 'Dealer_Master_Contract_2026.pdf',
        size: '2.4 MB',
        type: 'PDF',
        uploadedAt: '2026-01-15',
        uploadedBy: 'Sarah J.',
      },
      {
        id: 'doc-d2',
        name: 'Q2_Performance_Audit.xlsx',
        size: '1.1 MB',
        type: 'Excel',
        uploadedAt: '2026-07-02',
        uploadedBy: 'Sarah J.',
      }
    ]
  },
  {
    id: 'dealer-2',
    dealerCode: 'DLR-0891',
    name: 'Vanguard Auto',
    company: 'Vanguard Automotive LLC',
    contactPerson: 'Melissa Green',
    phone: '+1 (512) 555-0844',
    email: 'melissa@vanguardauto.com',
    location: 'Austin, TX',
    region: 'South',
    assignedStaffId: 'staff-4',
    assignedStaffName: 'Mike K.',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    totalLeads: 856,
    convertedLeads: 412,
    status: 'Inactive',
    lastActivity: '2 days ago',
    joinedDate: '2023-01-18',
    rating: 4.2,
    revenue: 1890000,
    tier: 'Gold',
    notes: [
      {
        id: 'dn-2',
        authorName: 'Mike K.',
        authorRole: 'Sales Representative',
        content: 'Paused lead intake temporarily during ERP software upgrade. Resuming next week.',
        createdAt: '2026-08-30 09:15',
      }
    ]
  },
  {
    id: 'dealer-3',
    dealerCode: 'DLR-1102',
    name: 'Elite Drive',
    company: 'Elite Drive Network',
    contactPerson: 'Jonathan Miller',
    phone: '+1 (303) 555-0144',
    email: 'deals@elitedrive.net',
    location: 'Denver, CO',
    region: 'West',
    assignedStaffId: 'staff-5',
    assignedStaffName: 'David R.',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    totalLeads: 2105,
    convertedLeads: 1390,
    status: 'Active',
    lastActivity: '4 hours ago',
    joinedDate: '2021-10-05',
    rating: 4.8,
    revenue: 5920000,
    tier: 'Platinum',
  },
  {
    id: 'dealer-4',
    dealerCode: 'DLR-0945',
    name: 'Sunrise Motors',
    company: 'Sunrise Automotive Partners',
    contactPerson: 'Carlos Ramos',
    phone: '+1 (404) 555-0377',
    email: 'carlos@sunrisemotors.com',
    location: 'Atlanta, GA',
    region: 'South',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Anna Smith',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    totalLeads: 289,
    convertedLeads: 179,
    status: 'Active',
    lastActivity: '1 hour ago',
    joinedDate: '2024-02-14',
    rating: 4.7,
    revenue: 1450000,
    tier: 'Silver',
  },
  {
    id: 'dealer-5',
    dealerCode: 'DLR-1220',
    name: 'Urban Drive',
    company: 'Urban Drive Holdings',
    contactPerson: 'Emily Thornton',
    phone: '+1 (617) 555-0911',
    email: 'emily@urbandrive.com',
    location: 'Boston, MA',
    region: 'East Coast',
    assignedStaffId: 'staff-1',
    assignedStaffName: 'John Doe',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    totalLeads: 215,
    convertedLeads: 118,
    status: 'Active',
    lastActivity: '3 hours ago',
    joinedDate: '2024-04-09',
    rating: 4.6,
    revenue: 980000,
    tier: 'Silver',
  },
  {
    id: 'dealer-6',
    dealerCode: 'DLR-0780',
    name: 'Pinnacle Fleet Solutions',
    company: 'Pinnacle Commercial Auto',
    contactPerson: 'Arthur Hayes',
    phone: '+1 (312) 555-0632',
    email: 'ahayes@pinnaclefleet.com',
    location: 'Chicago, IL',
    region: 'Midwest',
    assignedStaffId: 'staff-5',
    assignedStaffName: 'David R.',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    totalLeads: 620,
    convertedLeads: 390,
    status: 'Pending',
    lastActivity: '1 day ago',
    joinedDate: '2025-01-20',
    rating: 4.3,
    revenue: 1200000,
    tier: 'Bronze',
  }
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    leadCode: 'LD-8492',
    name: 'Elena Rodriguez',
    company: 'TechCorp Inc.',
    phone: '+1 (555) 019-2834',
    email: 'elena.r@techcorp.com',
    source: 'Website Form',
    assignedStaffId: 'staff-1',
    assignedStaffName: 'John Doe',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'New',
    priority: 'Urgent',
    createdDate: '2026-09-01',
    lastFollowUp: '2026-09-01 16:30',
    estimatedValue: 85000,
    location: 'San Francisco, CA',
    industry: 'Software & Technology',
    website: 'https://techcorp-sample.com',
    notes: [
      {
        id: 'n-1',
        authorName: 'John Doe',
        authorRole: 'Senior Account Exec',
        content: 'Elena is the VP of Procurement. Looking to onboard 5 regional branches by next quarter.',
        createdAt: '2026-09-01 16:35',
        pinned: true,
      }
    ],
    activities: [
      {
        id: 'act-1',
        type: 'created',
        title: 'Lead Created',
        description: 'Lead submitted via Website Inbound Enterprise Form.',
        timestamp: '2026-09-01 14:20',
        authorName: 'System Bot',
      },
      {
        id: 'act-2',
        type: 'assigned',
        title: 'Lead Assigned to John Doe',
        description: 'Auto-routed based on Western Region & Urgent priority tier.',
        timestamp: '2026-09-01 14:22',
        authorName: 'Assignment Engine',
      },
      {
        id: 'act-3',
        type: 'email',
        title: 'Introductory Email Sent',
        description: 'Sent standard Enterprise CRM overview & meeting link.',
        timestamp: '2026-09-01 16:30',
        authorName: 'John Doe',
      }
    ],
    followUps: [
      {
        id: 'fu-1',
        leadId: 'lead-1',
        leadName: 'Elena Rodriguez',
        type: 'Call',
        date: '2026-09-03',
        time: '10:00',
        assignedStaffId: 'staff-1',
        assignedStaffName: 'John Doe',
        notes: 'Follow up on introductory demo and discuss pricing tiers.',
        completed: false,
        priority: 'Urgent'
      }
    ],
    documents: [
      {
        id: 'doc-1',
        name: 'TechCorp_RFP_Requirements.pdf',
        size: '1.8 MB',
        type: 'PDF',
        uploadedAt: '2026-09-01',
        uploadedBy: 'Elena Rodriguez',
      }
    ]
  },
  {
    id: 'lead-2',
    leadCode: 'LD-8491',
    name: 'Marcus Chen',
    company: 'Global Trade Ltd',
    phone: '+1 (555) 482-9011',
    email: 'mchen@globaltrade.net',
    source: 'Trade Show',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Anna Smith',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'Contacted',
    priority: 'High',
    createdDate: '2026-08-31',
    lastFollowUp: '2026-09-01 11:00',
    estimatedValue: 120000,
    location: 'Houston, TX',
    industry: 'Logistics & Supply Chain',
    website: 'https://globaltrade-sample.net',
    notes: [
      {
        id: 'n-2',
        authorName: 'Anna Smith',
        authorRole: 'Regional Manager',
        content: 'Met at the National Auto & Equipment Expo. Wants custom dealer portal integration.',
        createdAt: '2026-08-31 18:00',
      }
    ],
    activities: [
      {
        id: 'act-21',
        type: 'created',
        title: 'Lead Captured at Trade Show',
        description: 'Scanned booth badge at Auto Expo 2026.',
        timestamp: '2026-08-31 15:40',
        authorName: 'Anna Smith',
      },
      {
        id: 'act-22',
        type: 'call',
        title: 'Discovery Phone Call',
        description: 'Spoke for 22 mins. Marcus confirmed budget approval for Q4 rollout.',
        timestamp: '2026-09-01 11:00',
        authorName: 'Anna Smith',
        meta: { duration: '22m', outcome: 'Positive' }
      }
    ],
    followUps: [
      {
        id: 'fu-2',
        leadId: 'lead-2',
        leadName: 'Marcus Chen',
        type: 'Meeting',
        date: '2026-09-04',
        time: '14:30',
        assignedStaffId: 'staff-2',
        assignedStaffName: 'Anna Smith',
        notes: 'Executive Demo with VP of Operations.',
        completed: false,
        priority: 'High'
      }
    ]
  },
  {
    id: 'lead-3',
    leadCode: 'LD-8490',
    name: 'Sarah Jenkins',
    company: 'Innovate Solutions',
    phone: '+1 (555) 392-1144',
    email: 'sarah.j@innovatesolutions.co',
    source: 'Referral',
    assignedStaffId: 'staff-1',
    assignedStaffName: 'John Doe',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'Qualified',
    priority: 'Medium',
    createdDate: '2026-08-29',
    lastFollowUp: '2026-08-31 14:00',
    estimatedValue: 64000,
    location: 'Portland, OR',
    industry: 'Consulting & Advisory',
    website: 'https://innovatesolutions-sample.co',
    notes: [
      {
        id: 'n-3',
        authorName: 'John Doe',
        authorRole: 'Senior Account Exec',
        content: 'Referred by Apex Motors. High intent customer, ready for proposal review.',
        createdAt: '2026-08-30 10:20',
      }
    ],
    activities: [
      {
        id: 'act-31',
        type: 'created',
        title: 'Referral Received',
        description: 'Referred by Robert Vance (Apex Motors).',
        timestamp: '2026-08-29 09:10',
        authorName: 'System',
      },
      {
        id: 'act-32',
        type: 'status_change',
        title: 'Status changed to Qualified',
        description: 'Lead passed BANT criteria (Budget, Authority, Need, Timeline).',
        timestamp: '2026-08-31 14:00',
        authorName: 'John Doe',
      }
    ],
    followUps: [
      {
        id: 'fu-3',
        leadId: 'lead-3',
        leadName: 'Sarah Jenkins',
        type: 'Contract Review',
        date: '2026-09-05',
        time: '11:00',
        assignedStaffId: 'staff-1',
        assignedStaffName: 'John Doe',
        notes: 'Review draft contract and service level terms.',
        completed: false,
        priority: 'Medium'
      }
    ]
  },
  {
    id: 'lead-4',
    leadCode: 'LD-8489',
    name: 'David Kim',
    company: 'Summit Financial',
    phone: '+1 (555) 902-8472',
    email: 'dkim@summitfinancial.com',
    source: 'Cold Call',
    assignedStaffId: '',
    assignedStaffName: 'Unassigned',
    assignedStaffAvatar: undefined,
    status: 'Lost',
    priority: 'Low',
    createdDate: '2026-08-25',
    lastFollowUp: '2026-08-28 09:30',
    estimatedValue: 45000,
    location: 'Denver, CO',
    industry: 'Banking & Financial',
    website: 'https://summitfinancial-sample.com',
    notes: [
      {
        id: 'n-4',
        authorName: 'Mike K.',
        authorRole: 'Sales Representative',
        content: 'Chose competitor due to existing legacy system contract lock-in until 2027.',
        createdAt: '2026-08-28 09:35',
      }
    ],
    activities: [
      {
        id: 'act-41',
        type: 'created',
        title: 'Outbound Prospect Created',
        description: 'Cold call outreach logged.',
        timestamp: '2026-08-25 11:00',
        authorName: 'Mike K.',
      },
      {
        id: 'act-42',
        type: 'status_change',
        title: 'Status marked as Lost',
        description: 'Client renewed current vendor contract.',
        timestamp: '2026-08-28 09:30',
        authorName: 'Mike K.',
      }
    ]
  },
  {
    id: 'lead-5',
    leadCode: 'LD-8488',
    name: 'Jessica Taylor',
    company: 'Velocity Motors',
    phone: '+1 (555) 774-2910',
    email: 'jtaylor@velocitymotors.com',
    source: 'Website Form',
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Sarah J.',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'Negotiation',
    priority: 'Urgent',
    createdDate: '2026-08-26',
    lastFollowUp: '2026-09-01 15:10',
    estimatedValue: 150000,
    location: 'Dallas, TX',
    industry: 'Automotive Dealership',
    website: 'https://velocitymotors-sample.com',
    notes: [
      {
        id: 'n-5',
        authorName: 'Sarah J.',
        authorRole: 'Sales Director',
        content: 'Negotiating multi-store discount. Ready to convert once SLA is signed.',
        createdAt: '2026-09-01 15:15',
        pinned: true,
      }
    ],
    activities: [
      {
        id: 'act-51',
        type: 'created',
        title: 'Inbound Request',
        description: 'Interested in becoming an authorized regional dealer.',
        timestamp: '2026-08-26 10:00',
        authorName: 'System',
      },
      {
        id: 'act-52',
        type: 'meeting',
        title: 'Commercial Terms Meeting',
        description: 'Discussed wholesale margins and lead attribution model.',
        timestamp: '2026-09-01 15:00',
        authorName: 'Sarah J.',
      }
    ],
    followUps: [
      {
        id: 'fu-5',
        leadId: 'lead-5',
        leadName: 'Jessica Taylor',
        type: 'Contract Review',
        date: '2026-09-02',
        time: '16:00',
        assignedStaffId: 'staff-3',
        assignedStaffName: 'Sarah J.',
        notes: 'Final contract signing and dealer conversion onboarding.',
        completed: false,
        priority: 'Urgent'
      }
    ]
  },
  {
    id: 'lead-6',
    leadCode: 'LD-8487',
    name: 'Thomas Wright',
    company: 'Horizon Fleet Group',
    phone: '+1 (555) 338-9921',
    email: 'twright@horizonfleet.com',
    source: 'Google Search',
    assignedStaffId: 'staff-4',
    assignedStaffName: 'Mike K.',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'Follow-up',
    priority: 'High',
    createdDate: '2026-08-27',
    lastFollowUp: '2026-08-30 16:45',
    estimatedValue: 92000,
    location: 'Phoenix, AZ',
    industry: 'Commercial Transportation',
    website: 'https://horizonfleet-sample.com',
    notes: [],
    activities: [
      {
        id: 'act-61',
        type: 'created',
        title: 'Organic Search Inbound',
        description: 'Lead downloaded Enterprise CRM whitepaper.',
        timestamp: '2026-08-27 13:15',
        authorName: 'System',
      }
    ],
    followUps: [
      {
        id: 'fu-6',
        leadId: 'lead-6',
        leadName: 'Thomas Wright',
        type: 'Demo',
        date: '2026-09-03',
        time: '15:00',
        assignedStaffId: 'staff-4',
        assignedStaffName: 'Mike K.',
        notes: 'Product walkthrough focusing on staff management module.',
        completed: false,
        priority: 'High'
      }
    ]
  },
  {
    id: 'lead-7',
    leadCode: 'LD-8486',
    name: 'Amanda Brooks',
    company: 'Prime Mobility',
    phone: '+1 (555) 662-8199',
    email: 'abrooks@primemobility.com',
    source: 'Partner',
    assignedStaffId: 'staff-5',
    assignedStaffName: 'David R.',
    assignedStaffAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'Converted',
    priority: 'Medium',
    createdDate: '2026-08-20',
    lastFollowUp: '2026-08-28 10:00',
    estimatedValue: 180000,
    location: 'Atlanta, GA',
    industry: 'Automotive Distribution',
    convertedToDealerId: 'dealer-4',
    notes: [
      {
        id: 'n-7',
        authorName: 'David R.',
        authorRole: 'CRM Specialist',
        content: 'Converted successfully into Dealer partner (Sunrise Motors Group).',
        createdAt: '2026-08-28 10:15',
      }
    ],
    activities: [
      {
        id: 'act-71',
        type: 'converted',
        title: 'Lead Converted to Dealer',
        description: 'Successfully onboarded as an authorized partner dealership.',
        timestamp: '2026-08-28 10:00',
        authorName: 'David R.',
      }
    ]
  }
];

export const INITIAL_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-main-1',
    type: 'converted',
    title: 'Lead #LD-8492 converted by Apex Auto Group.',
    description: 'Converted from Inbound Qualified lead to Premium Tier partner.',
    timestamp: '10 mins ago',
    authorName: 'Sarah J.',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'act-main-2',
    type: 'assigned',
    title: 'New lead assigned to Sunrise Motors.',
    description: 'Lead #LD-8491 (Marcus Chen) routed to regional distribution partner.',
    timestamp: '1 hour ago',
    authorName: 'Anna Smith',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'act-main-3',
    type: 'note',
    title: 'System generated weekly report.',
    description: 'Weekly Conversion & Pipeline Performance analytics compiled.',
    timestamp: '3 hours ago',
    authorName: 'System Analytics',
  },
  {
    id: 'act-main-4',
    type: 'created',
    title: 'New dealer Vanguard Auto onboarded.',
    description: 'Austin TX hub registered with 856 projected lead capacity.',
    timestamp: '5 hours ago',
    authorName: 'Mike K.',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'act-main-5',
    type: 'status_change',
    title: 'Lead #LD-8488 status changed to Negotiation.',
    description: 'Contract terms delivered to Velocity Motors leadership.',
    timestamp: '8 hours ago',
    authorName: 'Sarah J.',
    authorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'act-main-6',
    type: 'created',
    title: 'New staff member Rachel Taylor joined Enterprise Sales.',
    description: 'Assigned EMP-041 with initial quota of 50 enterprise accounts.',
    timestamp: '1 day ago',
    authorName: 'John Doe',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Urgent Lead Assigned',
    message: 'Elena Rodriguez (TechCorp Inc.) requires follow-up within 2 hours.',
    timestamp: '15 mins ago',
    read: false,
    type: 'lead',
    linkTab: 'leads',
    linkId: 'lead-1',
  },
  {
    id: 'notif-2',
    title: 'Dealer Conversion Milestone',
    message: 'Apex Motors completed their 800th converted lead for Q3.',
    timestamp: '1 hour ago',
    read: false,
    type: 'dealer',
    linkTab: 'dealers',
    linkId: 'dealer-1',
  },
  {
    id: 'notif-3',
    title: 'Upcoming Follow-up Scheduled',
    message: 'Demo with Marcus Chen scheduled for tomorrow at 2:30 PM.',
    timestamp: '3 hours ago',
    read: false,
    type: 'followup',
    linkTab: 'leads',
    linkId: 'lead-2',
  },
  {
    id: 'notif-4',
    title: 'Monthly Staff Performance Updated',
    message: 'August sales rankings and conversion scores have been published.',
    timestamp: '1 day ago',
    read: true,
    type: 'staff',
    linkTab: 'staff',
  }
];

export const INITIAL_SETTINGS: CRMSettings = {
  company: {
    name: 'Nexus CRM',
    tagline: 'Enterprise Suite for B2B Dealers & Lead Management',
    email: 'support@nexuscrm-enterprise.com',
    phone: '+1 (800) 555-0199',
    address: '1000 4th Ave, Suite 2400, Seattle, WA 98104',
    website: 'https://nexuscrm-enterprise.com',
    timezone: 'America/Los_Angeles (PST/PDT)',
    currency: 'INR (₹)',
    logoUrl: '',
  },
  leadConfig: {
    statuses: [
      { name: 'New', color: '#2563eb', isDefault: true },
      { name: 'Contacted', color: '#d97706' },
      { name: 'Follow-up', color: '#8b5cf6' },
      { name: 'Qualified', color: '#4f46e5' },
      { name: 'Negotiation', color: '#ea580c' },
      { name: 'Converted', color: '#16a34a' },
      { name: 'Lost', color: '#64748b' },
    ],
    sources: [
      'Website Form',
      'Trade Show',
      'Referral',
      'Cold Call',
      'Social Media',
      'Google Search',
      'Partner',
      'Email Campaign'
    ],
    autoAssignLeads: true,
    defaultPriority: 'Medium',
  },
  staffConfig: {
    roles: [
      'Sales Director',
      'Regional Manager',
      'Senior Account Exec',
      'Sales Representative',
      'CRM Specialist',
      'Support Lead'
    ],
    departments: [
      'Enterprise Sales',
      'Automotive Network',
      'Dealer Relations',
      'Commercial Accounts',
      'Inbound Growth',
      'Customer Success'
    ]
  },
  notifications: {
    emailAlerts: true,
    followUpReminders: true,
    leadAssignmentPush: true,
    dailyDigest: true,
    weeklyReportEmail: true,
  }
};
